/*
 * WDT_program.c
 *
 *  Created on: 1 Jul 2023
 *      Author: noor elswefy
 */
#include "STD_TYPES.h"
#include "BIT_MATH.h"
#include "WDT_config.h"
#include "WDT_private.h"
#include "WDT_interface.h"


void WDT_Enable()
{
	SET_BIT(WDTCR, WDTCR_WDE);

}
void WDT_disable()
{
	//1- write a logic one to WDTOE and WDE
	WDTCR = (1 << WDTCR_WDE) |	(1 << WDTCR_WDTOE);

	//2-Within the next four clock cycles, write a logic 0 to WDE
	WDTCR = 0;

}

void WDT_SLEEP( u8 Copyu8Timeout)
{
#if  WATCHDOG_TIMER_PRESCALE_SELECTION == TIMEOUT_16_K
	CLR_BIT(WDTCR, WDTCR_WDP2);
	CLR_BIT(WDTCR, WDTCR_WDP1);
	CLR_BIT(WDTCR, WDTCR_WDP0);
#elif WATCHDOG_TIMER_PRESCALE_SELECTION == TIMEOUT_32_K
	CLR_BIT(WDTCR, WDTCR_WDP2);
	CLR_BIT(WDTCR, WDTCR_WDP1);
	SET_BIT(WDTCR, WDTCR_WDP0);

#elif WATCHDOG_TIMER_PRESCALE_SELECTION == TIMEOUT_64_K
	CLR_BIT(WDTCR, WDTCR_WDP2);
	SET_BIT(WDTCR, WDTCR_WDP1);
	SET_BIT(WDTCR, WDTCR_WDP0);

#elif WATCHDOG_TIMER_PRESCALE_SELECTION == TIMEOUT_128_K
	SET_BIT(WDTCR, WDTCR_WDP2);
	CLR_BIT(WDTCR, WDTCR_WDP1);
	CLR_BIT(WDTCR, WDTCR_WDP0);

#elif WATCHDOG_TIMER_PRESCALE_SELECTION == TIMEOUT_512_K
	SET_BIT(WDTCR, WDTCR_WDP2);
	CLR_BIT(WDTCR, WDTCR_WDP1);
	SET_BIT(WDTCR, WDTCR_WDP0);

#elif WATCHDOG_TIMER_PRESCALE_SELECTION == TIMEOUT_1024_K
	SET_BIT(WDTCR, WDTCR_WDP2);
	SET_BIT(WDTCR, WDTCR_WDP1);
	CLR_BIT(WDTCR, WDTCR_WDP0);
#elif WATCHDOG_TIMER_PRESCALE_SELECTION == TIMEOUT_2048_K
	SET_BIT(WDTCR, WDTCR_WDP2);
	SET_BIT(WDTCR, WDTCR_WDP1);
	SET_BIT(WDTCR, WDTCR_WDP0);

#endif
}
